### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jsjadh** [EvilBytecode/PayloadCrypter#1]
how do i install it it gives me this 
github.com/EvilBytecode/GolangStyle/pkg
../go/pkg/mod/github.com/!evil!bytecode/!golang!style@v1.0.2/pkg/gostyle.go:14:33: undefined: syscall.NewLazyDLL
../go/pkg/mod/github.com/!evil!bytecode/!golang!style@v1.0.2/pkg/gostyle.go:82:20: undefined: syscall.Handle
../go/pkg/mod/github.com/!evil!bytecode/!golang!style@v1.0.2/pkg/gostyle.go:167:22: undefined: syscall.NewLazyDLL

**Comment by EvilBytecode** [comment]
are you on linux or on windows?

**Comment by EvilBytecode** [comment]
no response, closing.

**Comment by jsjadh** [comment]
> are you on linux or on windows?

kali linux

**Comment by EvilBytecode** [comment]
Then it wont work, it uses gostyle
